### PR TITLE
refactor: move PcrRef to models

### PR DESCRIPTION
**Pull request by alexche-cchange**

### CODE REVIEW

**Review by alexlitvinenko — COMMENTED** [review]
This is a major change. Reflect this fact in the commit message.

**Comment by alexche-cchange** [comment]
refactor! does trigger the major version update indeed.

**Review by alexlitvinenko — COMMENTED** [review]
LGTM. 
Don't forget to mention breaking changes somewhere (changelog?).
Search for `BREAKING CHANGE` in the [spec](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by alexche-cchange** [comment]
Alex, changelog is generated here from the commit messages. Current commit message `refactor!: move PcrRef to models` seems to be in line with recommendation from conventional commit (example from them: `feat!: send an email to the customer when a product is shipped`). I have also tested that commitizen iterates the major version - it will be 4.x after this change. I think we are good, no ?

**Review by corvis — APPROVED** [review]

**Pull request merged**
